apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: authrequests.dex.coreos.com
  labels:
    {{- include "dex-crds.labels" . | nindent 4 }}
spec:
  group: dex.coreos.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: authrequests
    singular: authrequest
    kind: AuthRequest
