{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  labels:
    app: {{ template "scaler.name" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["iguazio.com"]
  resources: ["iguaziotenantappservicesets"]
  verbs: ["*"]
- apiGroups: ["metrics.k8s.io", "custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
