{{- if .Values.mlrunPersistency.pv.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlrun-pv
  labels:
    app.kubernetes.io/name: {{ template "open-mlops.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: "mlrun-host-path"
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/{{ template "open-mlops.fullname" . }}-mlrun
{{- end -}}
