{{- if .Values.mlrunPersistency.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mlrun.api.volumes.storageOverride.persistentVolumeClaim.claimName }}
  labels:
    app.kubernetes.io/name: {{ template "open-mlops.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: "mlrun-host-path"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end -}}
