apiVersion: nuclio.io/v1beta1
kind: NuclioProject
metadata:
  name: {{ template "tsdb-functions.projectName" . }}
  labels:
    app.kubernetes.io/name: {{ template "tsdb-functions.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: "tsdb-functions"
    nuclio.io/project-name: {{ template "tsdb-functions.projectName" . }}
    app: {{ template "tsdb-functions.name" . }}  # TODO deprecate, use app.kubernetes.io/name instead
    chart: {{ template "tsdb-functions.chart" . }}
    release: {{ .Release.Name }}  # TODO deprecate, use app.kubernetes.io/instance instead
    heritage: {{ .Release.Service }}
    component: project
