{{- if .Values.crd.create }}
apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: scheduledworkflows.kubeflow.org
  labels:
    component: crd
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  group: kubeflow.org
  names:
    kind: ScheduledWorkflow
    listKind: ScheduledWorkflowList
    plural: scheduledworkflows
    shortNames:
    - swf
    singular: scheduledworkflow
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
{{- end }}
