{{- if .Values.crd.create }}
apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: viewers.kubeflow.org
  labels:
    component: crd
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  group: kubeflow.org
  names:
    kind: Viewer
    listKind: ViewerList
    plural: viewers
    shortNames:
    - vi
    singular: viewer
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
{{- end }}
