{{- if .Values.controller.crd.create }}

apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: iguaziotenants.iguazio.com
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: crd
spec:
  group: iguazio.com
  names:
    kind: IguazioTenant
    plural: iguaziotenants
    singular: iguaziotenant
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
{{- end }}
