apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "open-mlops.jupyter.fullname" . }}
  labels:
    app.kubernetes.io/component: jupyter-notebook
    app.kubernetes.io/name: {{ template "open-mlops.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jupyter-notebook
      app.kubernetes.io/name: {{ template "open-mlops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: jupyter-notebook
        app.kubernetes.io/name: {{ template "open-mlops.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
      initContainers:
      - name: init-chown-data
        # jupyter default NB user: uid=1000(jovyan) gid=100(users) groups=100(users)
        command: ["chown", "-R", "1000:100", "/home/jovyan/data"]
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /home/jovyan/data
          name: notebooks
      containers:
      - name: jupyter-notebook
        image: "{{ .Values.jupyterNotebook.image.repository }}:{{ .Values.jupyterNotebook.image.tag }}"
        imagePullPolicy: {{ .Values.jupyterNotebook.image.pullPolicy }}
        env:
        - name: MLRUN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: MLRUN_DBPATH
          value: {{ printf "http://%s:%s" (include "open-mlops.mlrun.api.fullname" .) (include "open-mlops.mlrun.api.port" .) }}
        - name: MLRUN_UI_URL
          value: {{ .Values.jupyterNotebook.mlrunUIURL }}
        - name: MLRUN_NUCLIO_DASHBOARD_URL
          value: {{ .Values.jupyterNotebook.nuclioDashboardURL }}
        - name: MLRUN_MPIJOB_CRD_VERSION
          value: {{ index .Values "mpi-operator" "crd" "version" }}
        - name: MLRUN_ARTIFACT_PATH
          value: "/home/jovyan/data"
        - name: MLRUN_PVC_MOUNT
          value: {{ printf "%s:/home/jovyan/data" (include "open-mlops.jupyter-pvc.fullname" .) }}
        - name: CHOWN_HOME
          value: "yes"
        - name: CHOWN_HOME_OPTS
          value: "-R"
        volumeMounts:
        - mountPath: /home/jovyan/data
          name: notebooks
        ports:
        - containerPort: 8888
        command: [ "start-notebook.sh" ]
        args:
        - --ip="0.0.0.0"
        - --port=8888
        - --NotebookApp.token=''
        - --NotebookApp.password=''
        - --NotebookApp.default_url="/lab"
      volumes:
      - name: notebooks
        persistentVolumeClaim:
          claimName: {{ template "open-mlops.jupyter-pvc.fullname" . }}
