{{- if .Values.deployment.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-configmap
  labels:
    component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 4 }}
data:
   viewer-pod-template.json:  |-
    {
        "spec": {
            "serviceAccountName": "kubeflow-pipelines-viewer"
        }
    }
{{- end }}
